global:
  # In this experiment, we only use the Insecta class from the iNaturalist dataset
  # Add more superclasses if you wish to use more classes
  included_classes: ["Insecta"]
  verbose: false
  overwrite: true

#Modify these paths to the dataset you want to use
paths:
  #path for the dataset you just downloaded
  src_dataset: "haute_garonne/Insecta"
  #path for the sub-dataset you want to do training and validation (e.g. haute_garonne)
  dst_dataset: "haute_garonne"

  #I am too lazy to change the path in the code, so I just put it here. Please don't touch it T.T
  web_crawl_output_json: "/home/quydx/tinyML/output/haute_garonne.json"
  output_dir: "output"

#In case you want to have more updated dataset, you can use the web_crawl to download the latest data from iNaturalist
#Else don't touch this part
web_crawl:
  total_pages: 104
  base_url: "https://www.inaturalist.org/check_lists/32961-Haute-Garonne-Check-List?page="
  delay_between_requests: 1.0

#Modify these parameters to your needs
train_val_split:
  train_size: 0.8
  random_state: 42
  dominant_threshold: 1.0
